-- Tabla USUARIO
CREATE TABLE USUARIO (
    IDUSU NUMBER NOT NULL,
    NOMUSU VARCHAR2(20)  NOT NULL,
    CONUSU VARCHAR2(15)  NOT NULL,
    NOMPER VARCHAR2(50)  NOT NULL,
    APEPER VARCHAR2(50)  NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY (IDUSU)
) ;


CREATE SEQUENCE SECUENCIAS1
START WITH 1
INCREMENT BY 1;

-- Creacion de los disparadores
-- Disparador para la tabla USUARIO
CREATE TRIGGER AUTOIDUSUARIO
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
SELECT SECUENCIAS1.NEXTVAL INTO :NEW.IDUSU FROM DUAL;
END;


INSERT INTO USUARIO       
	(NOMUSU,CONUSU,NOMPER,APEPER)
	 SELECT 'pedrito','Conater','Pedro','Collazos' FROM dual UNION ALL 
	 SELECT 'manu56','laslala','Manuel','Gonzales' FROM dual UNION ALL 
	 SELECT 'hemercito','Pistaa','Hernesto','Palomino' FROM dual;